--------------------------------------------------------
--  Datei erstellt -Sonntag-Juli-16-2017   
--------------------------------------------------------
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANREDE.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_ART.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_REFERENZ.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_RECHT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_RECHTE.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_ROLLE.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_RECHT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_RECHT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_ROLLE.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_TITEL.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANREDE_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_ANW_AAR_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_ART_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_REFERENZ_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_ARF_ANW_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_ARF_REFERENZ_ANW_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_BEN_ANR_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_BEN_TIT_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_BEN_AD_UPPER.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_RECHT_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_BRE_REC_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_BV_BENUTZER_RECHTE.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_BV_BENUTZER_RECHTE_APP.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_ROLLE_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_BRO_ROL_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_RECHT_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_REC_ANW_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_ROL_ANW_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_RECHT_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_RRE_REC_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_ROLLE_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\IDX_RRO_PARENT_ID_FK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_TITEL_PK.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\TRG_BV_ANREDE_BRIU.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\TRG_BV_ANWENDUNG_BRIU.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\TRG_BV_ANWENDUNG_ART_BRIU.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\TRG_BV_BENUTZER_BRIU.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\TRG_BV_RECHT_BRIU.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\TRG_BV_ROLLE_BRIU.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\TRG_BV_TITEL_BRIU.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANREDE_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_ART_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ANWENDUNG_REFERENZ_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_RECHT_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_BENUTZER_ROLLE_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_RECHT_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_RECHT_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_ROLLE_ROLLE_CONSTRAINT.sql
@Y:\GitHub\Benutzerverwaltung\Benutzerverwaltung\core\sql\tables\BV_TITEL_CONSTRAINT.sql
